version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      -  "6000:6000"
    environment:
      NODE_ENV: production,
      AWS_ACCESS_KEY_ID: 
      AWS_SECRET_ACCESS_KEY: 
      AWS_REGION: 
      OPENAI_API_KEY: 
      EVOLUTION_BASE_URL: 
      SUPABASE_PROJECT_URL: 
      SUPABASE_KEY: 
    volumes:
      - .:/app
      - ./logs:/app/logs 