version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      -  "7000:7000"
    environment:
      NODE_ENV: production,
      AWS_ACCESS_KEY_ID: 
      AWS_SECRET_ACCESS_KEY: 
      AWS_REGION: 
      OPENAI_API_KEY: 
      EVOLUTION_BASE_URL: 
      SUPABASE_PROJECT_URL: 
      SUPABASE_KEY: 
      SECRET_API_TOKEN:
      ADDRESS: "0.0.0.0"
      PORT: "7000"
    volumes:
      - .:/app
      - ./logs:/app/logs 